---
title: "UK Car Accidents 2005"    
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(devtools)
library(dplyr)
library(ggplot2)
library(lubridate)
library(flexdashboard)

accidents<-read.csv("Accidents0515.csv",header=TRUE,stringsAsFactors=FALSE)

df<-accidents

df$Date<-dmy(df$Date)

df<-df%>%
  filter(Date<="2005-12-31")%>%
  select(Day_of_Week)

df$Day_of_Week<-factor(df$Day_of_Week,levels=c("1","2","3","4","5","6","7"))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
ggplot()+
  geom_line(data=df,aes(x=Date,y=num_accidents))+
  ggtitle("Daily Number of Accidents 2005")+            
  xlab("Date")+
  ylab("Number of Accidents")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
ggplot()+
  geom_line(data=df,aes(x=Date,y=num_accidents))+
  ggtitle("Daily Number of Accidents December 2005")+            
  xlab("Date")+
  ylab("Number of Accidents") 
```

### Chart C

```{r}
ggplot()+
  geom_histogram(data=df,aes(x=Day_of_Week),stat="count",binwidth=0.5)+
  ggtitle("Chart C")+            
  xlab("Weekday")+
  ylab("Number of Accidents")
```

